'use client';
import {useRef,useState,type FormEvent} from 'react';
import {editorPayload,payloadEquals,periodDates,type Payload,type Snapshot,type Submission} from '@shared/shift-connected.mjs';
import {effectiveDay,dayOfWeek,dateLabel,timeLabel,DAY_LABELS,WEEKDAYS,validTime,type Day,type Baseline} from '@shared/shift-trial.mjs';
import type {Call} from './shift-workspace';
import styles from '@trial-style';
const shortLabels={unknown:'未登録',off:'入れない',rest:'休み希望',available:'入れる',want:'入りたい'};

export default function ShiftEditor({snapshot,name,proxyId,readOnly=false,call,onDirty,reload,onBusy,onSubmitted}:{snapshot:Snapshot;name:string;proxyId?:string;readOnly?:boolean;call:Call;onDirty:(dirty:boolean)=>void;reload:()=>void;onBusy?:(busy:boolean)=>void;onSubmitted?:(submitted:Submission)=>void}){
  const [stored,setStored]=useState(snapshot);const [payload,setPayload]=useState<Payload>(()=>editorPayload(snapshot));
  const [busy,setBusy]=useState(false);const [conflict,setConflict]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [baseline,setBaseline]=useState<Baseline>(payload.baseline);const [date,setDate]=useState(snapshot.period.starts_on);const [day,setDay]=useState<Day>({status:'available',start:'17:00',end:'22:00',nextDay:false});const [useDefault,setUseDefault]=useState(false);
  const profileDialog=useRef<HTMLDialogElement>(null);const dayDialog=useRef<HTMLDialogElement>(null);const mutation=useRef(false);
  const [openedAt]=useState(()=>Date.now());
  const period=stored.period;const dates=periodDates(period);const canEdit=!readOnly&&!conflict&&(!!proxyId||(period.state==='collecting'&&openedAt<new Date(period.deadline).getTime()));
  const unsaved=!payloadEquals(payload,editorPayload(stored));
  const needsSubmit=!stored.submitted||!payloadEquals(payload,stored.submitted.payload);
  function change(next:Payload){setPayload(next);onDirty(!payloadEquals(next,editorPayload(stored)));setNotice('変更しました。最後に下書き保存、または提出してください。');setError('');}
  function timeFields(value:Day,setValue:(value:Day)=>void){return <><div className={styles.timeFields}><label>開始<input type="time" aria-label="開始時刻" required value={value.start||''} onChange={e=>setValue({...value,start:e.target.value})}/></label><span>〜</span><label>終了<input type="time" aria-label="終了時刻" required value={value.end||''} onChange={e=>setValue({...value,end:e.target.value})}/></label></div><label className={styles.check}><input type="checkbox" checked={!!value.nextDay} onChange={e=>setValue({...value,nextDay:e.target.checked})}/>終了は翌日</label></>;}
  function openDay(value:string){setDate(value);const existing=effectiveDay(payload.baseline,payload.days,value);setDay({status:existing.status==='unknown'?'available':existing.status,start:existing.start||payload.baseline.start,end:existing.end||payload.baseline.end,nextDay:existing.nextDay||false});setUseDefault(!payload.days[value]);setError('');dayDialog.current?.showModal();}
  function saveDay(e:FormEvent){e.preventDefault();if(!useDefault&&!validTime(day)){setError('開始と終了の時刻を確認してください。');return;}const days={...payload.days};if(useDefault)delete days[date];else days[date]=day.status==='off'?{status:'off'}:day;change({...payload,days});dayDialog.current?.close();}
  function saveBaseline(e:FormEvent){e.preventDefault();if(!validTime({...baseline,status:'available'})||(baseline.kind==='fixed'&&baseline.weekdays.length===0)){setError('曜日と開始・終了時刻を確認してください。');return;}change({...payload,baseline});profileDialog.current?.close();}
  async function save(submit:boolean){
    if(mutation.current||!canEdit)return;mutation.current=true;setBusy(true);onBusy?.(true);setError('');setNotice('');
    let next=stored;
    try{
      if(proxyId){const submitted=await call('proxySubmit',{periodId:period.id,staffId:proxyId,expectedSubmissionVersion:stored.submitted?.version||0,payload}) as Submission;next={...stored,submitted};}
      else{
        if(unsaved||!stored.draft){const draft=await call('saveDraft',{periodId:period.id,expectedDraftVersion:stored.draft?.version||0,payload}) as NonNullable<Snapshot['draft']>;next={...stored,draft};setStored(next);onDirty(false);}
        if(submit){const submitted=await call('submit',{periodId:period.id,expectedDraftVersion:next.draft?.version||0,expectedSubmissionVersion:stored.submitted?.version||0}) as Submission;next={...next,submitted};}
      }
      setStored(next);onDirty(false);if(submit&&next.submitted)onSubmitted?.(next.submitted);setNotice(submit?'希望を提出しました。締切までは変更して再提出できます。':'下書きを保存しました。管理者にはまだ共有されていません。');
      if(proxyId)setNotice('代理で希望を提出しました。本人の下書きは保持されています。');
    }catch(caught){const failure=caught as Error&{code?:string};setError(failure.message||'保存できませんでした。');if(failure.code==='SHIFT_CONFLICT'||failure.code==='SHIFT_CLOSED')setConflict(true);}
    finally{mutation.current=false;setBusy(false);onBusy?.(false);}
  }
  return <>
    <div className={styles.heading}><div><h1>{readOnly?`${name}さんの提出内容`:proxyId?`${name}さんの希望を代理入力`:'勤務希望を提出'}</h1><p className={styles.periodTitle}>{period.starts_on}〜{period.ends_on}</p></div><span className={stored.submitted?styles.done:styles.draft}>{stored.submitted?'提出済み':'未提出'}</span></div>
    {proxyId&&<aside className={styles.proxyNote}>口頭で確認した内容を入力してください。本人の未提出の下書きは表示・変更されません。</aside>}
    {error&&<div role="alert" className={styles.error}>{error}{conflict&&<div className={styles.actions}><button className={styles.secondary} onClick={reload}>入力を控えて、最新の内容を読み込む</button></div>}</div>}
    {notice&&<div role="status" className={styles.success}>{notice}</div>}
    {readOnly&&!stored.submitted?<section className={styles.card}><p>まだ希望が届いていません。勤務可能な日は確認できません。</p></section>:<>
      <section className={styles.profileCard}><div className={styles.sectionTitle}><h2>普段の働き方</h2>{!readOnly&&<button className={styles.textButton} disabled={!canEdit||busy} onClick={()=>{setBaseline(structuredClone(payload.baseline));profileDialog.current?.showModal();}}>変更する</button>}</div><strong>{payload.baseline.kind==='fixed'?payload.baseline.weekdays.slice().sort().map(d=>WEEKDAYS[d]).join('・')+'曜日':'毎回、入れる日を選ぶ'}</strong>{payload.baseline.kind==='fixed'&&<span className={styles.profileTime}>{timeLabel({...payload.baseline,status:'available'})}</span>}<p>{payload.baseline.targetUnit==='week'?'週':'月'}{payload.baseline.target}日程度、働きたい</p></section>
      <section className={styles.calendarCard}><div className={styles.sectionTitle}><h2>今回の勤務希望</h2><span className={needsSubmit?styles.draft:styles.done}>{needsSubmit?'提出前の内容':'提出済みの内容'}</span></div><p className={styles.help}>変えたい日を押してください。空白の日は「未登録」のまま届きます。</p><div className={styles.legend}><span><i className={styles.availableDot}/>入れる</span><span><i className={styles.wantDot}/>入りたい</span><span><i className={styles.restDot}/>休み希望</span><span><i className={styles.offDot}/>入れない</span></div>
        <div className={styles.calendar} aria-label="勤務希望カレンダー">{WEEKDAYS.map(d=><div key={d} className={styles.weekday}>{d}</div>)}{Array.from({length:dayOfWeek(dates[0])},(_,i)=><div key={`blank-${i}`}/>)}{dates.map(d=>{const value=effectiveDay(payload.baseline,payload.days,d);return <button key={d} className={`${styles.day} ${styles[value.status]}`} disabled={!canEdit||busy} aria-label={`${dateLabel(d)} ${DAY_LABELS[value.status]} ${timeLabel(value)}`} onClick={()=>openDay(d)}><b>{Number(d.slice(8))}</b><span>{shortLabels[value.status]}</span><small>{value.start||'—'}</small></button>;})}</div><p className={styles.help}>これは勤務希望です。出勤日が確定したことを示すものではありません。</p>
      </section>
      {!readOnly&&<section className={styles.submitPanel}><p>提出締切：{new Intl.DateTimeFormat('ja-JP',{timeZone:period.timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(period.deadline))}</p><div className={styles.actions}>{!proxyId&&<button className={styles.secondary} disabled={!canEdit||busy||(!unsaved&&!!stored.draft)} onClick={()=>void save(false)}>下書きを保存する</button>}<button className={styles.primary} disabled={!canEdit||busy||(!needsSubmit&&!proxyId)} onClick={()=>void save(true)}>{busy?'保存しています…':!canEdit?'受付状況を確認してください':proxyId?'代理入力した希望を提出する':stored.submitted?'変更した希望を再提出する':'希望を提出する'}</button></div><small>下書きは本人だけに表示されます。提出すると管理者に共有されます。</small>{!dirtyOrSubmitted()&&<small>普段の働き方・希望日数も確認してください。</small>}</section>}
    </>}
    <dialog ref={profileDialog} className={styles.dialog}><form onSubmit={saveBaseline}><div className={styles.sectionTitle}><h2>普段の働き方</h2><button type="button" className={styles.closeButton} aria-label="閉じる" onClick={()=>profileDialog.current?.close()}>×</button></div>{error&&<p role="alert">{error}</p>}<label className={styles.formLabel}>働き方<select value={baseline.kind} onChange={e=>setBaseline({...baseline,kind:e.target.value as Baseline['kind']})}><option value="fixed">普段の曜日・時間が決まっている</option><option value="variable">毎回、入れる日を選ぶ</option></select></label>{baseline.kind==='fixed'&&<fieldset className={styles.weekdayChoices}><legend>普段働く曜日</legend>{WEEKDAYS.map((d,i)=><label key={d}><input type="checkbox" checked={baseline.weekdays.includes(i)} onChange={e=>setBaseline({...baseline,weekdays:e.target.checked?[...baseline.weekdays,i]:baseline.weekdays.filter(w=>w!==i)})}/><span>{d}</span></label>)}</fieldset>}{timeFields({...baseline,status:'available'},value=>setBaseline({...baseline,start:value.start||'',end:value.end||'',nextDay:!!value.nextDay}))}<fieldset className={styles.targetFields}><legend>働きたい日数の目安</legend><div className={styles.inlineFields}><label>単位<select value={baseline.targetUnit} onChange={e=>setBaseline({...baseline,targetUnit:e.target.value as Baseline['targetUnit'],target:Math.min(baseline.target,e.target.value==='week'?7:31)})}><option value="week">週</option><option value="month">月</option></select></label><label>日数<input type="number" min="0" max={baseline.targetUnit==='week'?7:31} step="1" required value={baseline.target} onChange={e=>setBaseline({...baseline,target:Number(e.target.value)})}/></label></div></fieldset><button className={styles.primary}>入力に反映する</button></form></dialog>
    <dialog ref={dayDialog} className={styles.dialog}><form onSubmit={saveDay}><div className={styles.sectionTitle}><h2>{dateLabel(date)}の希望</h2><button type="button" className={styles.closeButton} aria-label="閉じる" onClick={()=>dayDialog.current?.close()}>×</button></div>{error&&<p role="alert">{error}</p>}<label className={styles.check}><input type="checkbox" checked={useDefault} onChange={e=>setUseDefault(e.target.checked)}/>普段の条件を使う（今回の変更を解除）</label><fieldset disabled={useDefault} className={styles.dayChoices}><legend>この日の希望</legend>{(['available','want','rest','off'] as const).map(status=><label key={status}><input type="radio" name="day-status" value={status} checked={day.status===status} onChange={()=>setDay({...day,status})}/><span>{DAY_LABELS[status]}</span></label>)}</fieldset>{!useDefault&&day.status!=='off'&&timeFields(day,setDay)}<button className={styles.primary}>入力に反映する</button></form></dialog>
  </>;
  function dirtyOrSubmitted(){return unsaved||!!stored.submitted||!!stored.draft;}
}
