export type Mode = 'month' | 'week';
export type DayStatus = 'unknown' | 'off' | 'rest' | 'available' | 'want';
export type Day = { status: DayStatus; start?: string; end?: string; nextDay?: boolean; source?: string };
export type Baseline = { kind: 'fixed' | 'variable'; weekdays: number[]; start: string; end: string; nextDay: boolean; target: number; targetUnit: 'week' | 'month' };
export type Person = { id: string; name: string; baseline: Baseline; draft: Record<string, Day>; draftTouched: boolean; proxyDraft: null | { baseline: Baseline; draft: Record<string, Day> }; submitted: null | { baseline: Baseline; days: Record<string, Day>; version: number; proxy: boolean } };
export type Trial = { version: number; mode: Mode; stage: 'collecting' | 'closed' | 'published'; people: Person[]; notices: { id: number; to: string; kind: string; text: string }[]; nextId: number; reminded: string[]; assignments: Record<string, Record<string, Day>>; needs: Record<string, number>; changes: { id: number; personId: string; date: string; day: Day; status: 'pending' | 'approved' | 'declined' }[] };
export type Action = { type: string; personId?: string; baseline?: Baseline; date?: string; day?: Day | null; proxy?: boolean; consulted?: boolean; count?: number; id?: number; approve?: boolean };
export const WEEKDAYS: string[];
export const DAY_LABELS: Record<DayStatus, string>;
export const PERIODS: Record<Mode, { label: string; start: string; end: string; deadline: string; reminder: string }>;
export function datesFor(mode: Mode): string[];
export function dayOfWeek(date: string): number;
export function dateLabel(date: string): string;
export function timeLabel(day: Day): string;
export function validTime(day: Day): boolean;
export function effectiveDay(baseline: Baseline, changes: Record<string, Day>, date: string): Day;
export function submittedDay(person: Person, date: string): Day;
export function hasDraftChanges(person: Person): boolean;
export function createTrial(mode?: Mode): Trial;
export function applyTrial(state: Trial, action: Action): Trial;
